# render-api.yaml - Configuration for API service only
services:
  - type: web
    name: class-tracker-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "npm install --omit=dev"
    startCommand: "npm run start:api"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      
      # Database Configuration
      - key: CONNECTION_STRING
        value: mongodb+srv://admin:admin@jorgecluster.do6prwp.mongodb.net/mycontacts-backend?retryWrites=true&w=majority&appName=jorgecluster
      
      # Authentication
      - key: ACCESS_TOKEN_SECRET
        value: jorge123
      
      # Python/Playwright for class lookup (still needed for API)
      - key: DISPLAY
        value: ":99"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/ms-playwright"
    
    # Health check configuration
    healthCheckPath: /health
    
    # Auto-deploy from main branch
    autoDeploy: true